Use DSFR footer
MTES-MCT/mobilic pull request #160
Opened 2022-05-17 13:08 UTC by sandrica89

2022-05-17 13:52 UTC, rtaieb commented
Le logo France Relance me semble bien lourd : les 169Ko peuvent être pas mal réduit avec des sites comme https://squoosh.app/ par exemple

2022-05-17 15:03 UTC, rtaieb requested changes
Quelques petits commentaires, dont un seul de bloquant, sur le fichier footer_old.js :)

2022-05-17 15:03 UTC, rtaieb commented on web/landing/footer_old.js
> +import React from "react";
:red_circle: A supprimer :smile:

2022-05-17 16:14 UTC, sandrica89 commented on common/utils/theme.js
> +  // TODO: use dsfr style instead of mui
Oui, mais quand on mettra tout en DSFR, ce fichier tout entier sera supprimé donc je le retire :+1:

2022-05-17 16:27 UTC, sandrica89 commented
> Le logo France Relance me semble bien lourd : les 169Ko peuvent être pas mal réduit avec des sites comme https://squoosh.app/ par exemple

Je l'avais pourtant fait pour le logo EU :( 
Désolée pour cette PR pleine de code inutile. Ça m'apprendra à ne pas me review avant de request !

2022-05-17 16:44 UTC, sandrica89 commented on web/landing/ResourcePage/ResourcePage.js
>          <Typography variant={"h3"} className={classes.resourceSubtitle}>
Le `scrollTo(0,0)` sur le HTMLElement ne fonctionne plus :shrug: c'est surement pour la même raison que le header n'est plus sticky. Ne comprenant pas d'où ça vient, je l'ai remplacé par `window.scrollTo(0, 0)`

2022-05-18 07:22 UTC, rtaieb approved these changes
:+1:

2022-05-18 10:23 UTC, sandrica89 commented
Il reste un soucis sur la page de saisie de temps : sa hauteur est trop petite.

2022-05-19 12:54 UTC, merged