cFeat/registering several companies at once
MTES-MCT/mobilic pull request #195
Opened 2022-08-02 10:32 UTC by tristan-gueguen

https://trello.com/c/3i7AxIdW/706-probl%C3%A8me-du-rattachement-des-%C3%A9tablissements-%C3%A0-la-cr%C3%A9ation-du-compte

2022-08-02 15:48 UTC, rtaieb requested changes
quelques remarques mineures, mais mes tests fonctionnels sont ok :+1:

2022-08-02 15:48 UTC, rtaieb commented on web/signup/company/CompanySignup.js
>          sirets: []
:orange_circle: idem commentaire back, ce paramètre est peut être devenu inutile

2022-08-02 15:48 UTC, rtaieb commented on web/signup/company/FacilityInfo.js
> +      className={selected ? classes.selectedFacility : ""}
:orange_circle: lorsque je sélectionne un établissement, dans Chrome, le composant se centre, si je le désélectionne, il revient à gauche. Je ne pense pas que ça soit voulu.

2022-08-02 15:48 UTC, rtaieb commented on web/signup/company/CompanySignup.js
> +      console.log(apiResponse.data);
:red_circle: à supprimer

2022-08-02 15:48 UTC, rtaieb commented on web/signup/company/AlreadyRegisteredSirets.js
> +        <InfoItem
:orange_circle: Cette info s'affiche également si j'ai déjà un compte et que je veux rajouter une entreprise déjà existante à partir de l'interface gestionnaire.
==> Le wording du mail de vérification n'est du coup pas correct.

De plus le texte dans ce composant apparaît centré, ça ne respecte pas le même format que les autres messages d'infos qui sont alignés à gauche

2022-08-02 17:59 UTC, tristan-gueguen commented on web/signup/company/AlreadyRegisteredSirets.js
> +        <InfoItem
Effectivement, je vais demander à audrey si on peut enlever cette partie du message

2022-08-08 07:43 UTC, rtaieb approved these changes

2022-08-08 07:58 UTC, merged