Feat/controller history page
MTES-MCT/mobilic pull request #216
Opened 2022-09-08 12:34 UTC by tristan-gueguen

https://trello.com/c/GgvtnXgg/635-visualiser-les-donn%C3%A9es-des-contr%C3%B4les-historiques-50

2022-09-09 16:42 UTC, rtaieb requested changes
Une seule remarque un peu bloquante, sinon que des petits détails.

2022-09-09 16:42 UTC, rtaieb commented on common/utils/time.js
> +export function prettyFormatDayFromDate(date, withYear = false) {
:green_circle: Pour alléger un peu le code et pour ne pas rajouter des méthodes qui font à peu près la même chose, je supprimerais les trois méthodes "prettyFormat..." que tu as rajoutées, et j'appellerai les méthodes existantes en ayant au préalable transformé ta date avec `date.getTime() / 1000` dans la méthode *getPrettyDate* du fichier ControlsList. D'ailleurs cette méthode *getPrettyDate* peut être qu'on peut la déplacer dans time.js ?

2022-09-09 16:42 UTC, rtaieb commented on web/controller/components/history/Filters.js
> +import React from "react";
:green_circle: Je renommerais ce fichier `ControllerHistoryFilters.js`, c'est plus pratique à retrouver quand tu cherches un fichier via les raccourci clavier :nerd_face:

2022-09-09 16:42 UTC, rtaieb commented on web/controller/components/history/Filters.js
> +          <SelectDsfr
:green_circle: Il me semble selon le Figma que ce select box sera à rajouter plus tard.

2022-09-09 16:42 UTC, rtaieb commented on web/controller/components/history/ControllerHistory.js
> +    fromDate: isoFormatLocalDate(addDaysToDate(new Date(), -2)),
:orange_circle: il faut remonter au début du mois en cours et pas seulement à J-2 (selon un commentaire dans le Figma)

2022-09-09 16:42 UTC, rtaieb commented on web/controller/components/list/ControlsList.js
> +      getGroupByKey(new Date(control.qrCodeGenerationTime * 1000), period)
:green_circle: Je prendrais plutôt la creationTime que la qrCodeGenerationTime. Peut être à voir avec Audrey ce qui paraitrait le plus logique pour un contrôleur.

2022-09-09 16:42 UTC, rtaieb commented on web/controller/components/list/ControlsList.js
> +    for (const date in controlsGroupedByPeriod) {
:red_circle: Ca ne fonctionne pas pour le filtre par mois, je me retrouve avec autant de lignes "septembre 2022" que j'ai de contrôle

2022-09-12 08:42 UTC, tristan-gueguen commented on web/controller/components/history/Filters.js
> +          <SelectDsfr
Que penses-tu de laisser la select box pour le moment et de ne laisser qu'une seule option ?

2022-09-12 08:49 UTC, tristan-gueguen commented on web/controller/components/list/ControlsList.js
> +    for (const date in controlsGroupedByPeriod) {
Ah bon ? Je ne reproduis pas ce problème de mon côté

2022-09-12 15:20 UTC, merged