Working team filter in activities tab
MTES-MCT/mobilic pull request #324
Opened 2023-03-08 11:05 UTC by rtaieb

https://trello.com/c/Sfb9eO7F/1001-adaptation-section-activit%C3%A9s-pour-mode-%C3%A9quipe

Je n'ai pas fait le filtre dans la modale d'export car il y a déjà des incohénrences entre le filtre "société" et le filtre "employé".
Je vais poser une question dans Trello, mais en attendant le filtre est fonctionnel dans dans l'onglet Activité.

2023-03-10 13:16 UTC, tristan-gueguen commented
Quelques bugs détectés en local:
<hr/>
Si je me place sur l'onglet Saisies A Valider et que je rafraichis la page, le filtre Equipe n'apparait pas (il faut changer d'onglet et revenir pour le voir)
Meme chose pour l'onglet Activites
<hr/>

- Je vais dans Saisies a valider, je selectionne une equipe, je la deselectionne
- Je change d'onglet et je reviens => J'ai un employee de selectionne dans le filtre

<hr/>

- Je vais dans Saisies a valider, je selectionne User 0, User 1 et User 2
- Je change d'onglet et je reviens => J'ai user 0 et user 1 de selectionnes
- Je deselectionne user 1
- Je change d'onglet et je reviens => j'ai user 0 et user 2 de selectionnes
Il semble que la derniere selection n'est pas prise en compte ?

2023-03-10 13:45 UTC, tristan-gueguen requested changes

2023-03-10 13:45 UTC, tristan-gueguen commented on web/admin/panels/Activities.js
> +  const handleUserFilterChange = newUsers => {
:green_circle:  On peut peut-etre mettre en commun ce bloc avec le bloc similaire dans Validations ?

2023-03-10 13:45 UTC, tristan-gueguen commented on web/admin/panels/Activities.js
> +    setUsers(newUsers);
:orange_circle:  Est-ce que cette ligne ne declenche pas le useEffect de la ligne 160 ? (On ne dispatche pas 2 fois l'ADMIN_ACTION du coup ?)

2023-03-10 13:45 UTC, tristan-gueguen commented on web/admin/panels/Validations.js
>        payload: { teams: unselectedTeams, users: users }
```suggestion
      payload: { teams: unselectedTeams, users: newUsers }
```
:red_circle: je pense que certains des bugs que j'ai decrit viennent de la

2023-03-13 13:22 UTC, rtaieb commented on web/admin/panels/Activities.js
> +  const handleUserFilterChange = newUsers => {
tu as raison, j'ai mis factorisé des fonctions que j'ai mis dans team.js

2023-03-13 13:22 UTC, rtaieb commented on web/admin/panels/Activities.js
> +    setUsers(newUsers);
si, le useEffect l.160 était un reliquat que j'aurais dû enlever. :+1:

2023-03-14 08:40 UTC, tristan-gueguen approved these changes

2023-03-14 10:51 UTC, merged