Apply privacy policy for cookie
MTES-MCT/mobilic pull request #342
Opened 2023-04-27 17:22 UTC by sandrica89

https://trello.com/c/qqo4mJAQ/1019

2023-04-28 09:50 UTC, rtaieb commented on web/common/LiveChat.js
> +        Besoin d'aide ?
:orange_circle: On a déjà eu quelques plaintes de gestionnaires qui n'arrivaient pas à cliquer sur certains boutons car ils étaient masqués par le bouton de CRISP. Le bouton Besoin d'aide est encore plus large, il peut donc poser de nouveaux problèmes.
Je vois plusieurs possibilités :
- déplacer le bouton dans la partie gauche de l'écran, qui est moins utilisé dans notre app.
- remettre une largeur de bouton comparable à celle de CRISP
- avoir une petite icone "croix" en au à droite de ce bouton pour le faire disparaître si besoin.

2023-04-28 09:57 UTC, rtaieb requested changes
Juste une remarque un peu bloquante pour l'interface CTT, où l'on voit désormais deux boutons "besoin d'aide" avec deux comportements différents.

2023-04-28 09:57 UTC, rtaieb commented on web/root.js
> +      {process.env.REACT_APP_CRISP_WEBSITE_ID && <LiveChat />}
:red_circle: 
Dans l'interface CTT, on a un doublon de bouton "Besoin d'aide" avec des comportements différents. Il faudrait trouver un moyen de rendre le tout moins confusant. (peut être rajouté une entrée dans la modale d'aide spéciale CTT pour ouvrir le chat CRISP ?)

2023-04-28 10:10 UTC, rtaieb commented on web/common/LiveChat.js
> +      <Button
:red_circle: Une fois la fenêtre de chat ouverte, je ne peux pas écrire de message. Je n'ai pas le champ texte pour le faire.

2023-05-05 11:53 UTC, sandrica89 commented on web/common/LiveChat.js
> +        Besoin d'aide ?
J'ai repris l'icône de crisp et ai ajouté une croix. À noter que la croix n'est pas dispo une fois que c'est l'icône de crisp qui prend le relai (mais on pourrait sans doute l'ajouter même dans ce cas :thinking:)

2023-05-05 11:54 UTC, sandrica89 commented on web/root.js
> +      {process.env.REACT_APP_CRISP_WEBSITE_ID && <LiveChat />}
J'ai supprimé le chat crisp pour les controleurs. Je n'ai pas ajouté la section dans l'aide.

2023-05-05 11:56 UTC, sandrica89 commented on web/common/LiveChat.js
> +      <Button
Je n'ai pas réussi à corriger ce problème. Je pense que cela ne fonctionne pas car la fenêtre de chat est ouverte avant que le script soit chargé.

J'ai tenté ceci :

```
    Crisp.load();
    Crisp.setOnLoadCallback("load", function() {
      Crisp.chat.show();
      Crisp.chat.open();
    });
```

mais j'ai toujours une erreur dans la console.

2023-05-22 14:37 UTC, merged