BDC save step 3
MTES-MCT/mobilic pull request #347
Opened 2023-05-10 14:25 UTC by rtaieb

https://trello.com/c/NuPhRqLb/1079

2023-05-25 13:12 UTC, sandrica89 commented on web/controller/components/bulletinControle/ControllerControlBulletinControleLIC.js
> +          />
:orange_circle:   Dans le cas d'un qr code Mobilic, `licPaperPresented` vaut quoi ? :thinking: 

:green_circle: Si `controlBulletin.licPaperPresented = null`, on pourrait check par défaut "oui" si `controlType` est `lic_papier` et "non" si `sans_lic`.

2023-05-25 13:21 UTC, sandrica89 commented on web/controller/components/bulletinControle/ControllerControlBulletinControleLIC.js
> +          label="Date de naissance"
```suggestion
          label="Date de naissance du salarié"
```

2023-05-25 13:23 UTC, sandrica89 commented on web/controller/components/bulletinControle/ControllerControlBulletinControleLIC.js
> +          selected={controlBulletin.userNationality}
:green_circle:
```suggestion
          selected={controlBulletin.userNationality || "FRA"}
```

2023-05-25 13:46 UTC, sandrica89 requested changes

2023-05-25 13:46 UTC, sandrica89 commented on web/controller/components/bulletinControle/ConfirmationCancelControlBulletinModal.js
> +      cancelButtonLabel="Annuler mes modifications"
:orange_circle: Il me semble que c'est l'inverse. C'est confusant dans le code : ici on demande de confirmer l'annulation :D 
Le plus clair serait sans doute de mettre "Enregistrer" en bouton principal (à priori on veut plutôt inciter l'utilisateur à enregistrer non ?)

2023-05-25 14:27 UTC, sandrica89 commented on web/controller/components/bulletinControle/ConfirmationCancelControlBulletinModal.js
> +      cancelButtonLabel="Annuler mes modifications"
Ne pas prendre en compte cette remarque, cela fonctionne correctement sur la branche no lic

2023-05-25 15:20 UTC, sandrica89 commented
:orange_circle: Il y a un warning dans la console à l'ouverture du drawer du bulletin de contrôle : 
> Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.

2023-05-30 09:41 UTC, rtaieb commented on web/controller/components/bulletinControle/BulletinControleDrawer.js
>    const closeDrawer = (forceClose = false) => {
si c'est utilisé, dans le cas où on vient d'enregistrer le formulaire, pour éviter que la popup "vous avez des modifications non enregistrées" s'affiche.

2023-05-30 09:41 UTC, rtaieb commented on web/controller/components/bulletinControle/ControllerControlBulletinControleLIC.js
> +      <Stack key={20} direction="column" p={2} sx={{ width: "100%" }}>
effectivement. C'est fait.

2023-06-02 07:47 UTC, merged