Add user controls section
MTES-MCT/mobilic pull request #348
Opened 2023-05-11 13:19 UTC by rtaieb

https://trello.com/c/XPktEreK/1033-section-contr%C3%B4les-en-bord-de-route

2023-05-15 09:10 UTC, tristan-gueguen commented
:red_circle: Est-ce qu'on n'afficherait pas les temps en passant à la ligne comme sur la maquette dans le ticket ? En l'état, il n'y a pas suffisament de place sur mobile pour afficher un contrôle (et il faudrait aligner horizontalement)
![Screenshot from 2023-05-15 11-05-01](https://github.com/MTES-MCT/mobilic/assets/77248807/4330340d-2bd2-4a53-87fd-3a60eb0e7411)
![Screenshot from 2023-05-15 11-01-46](https://github.com/MTES-MCT/mobilic/assets/77248807/d98dc289-c0b1-49ee-b300-d85d99203f29)

2023-05-15 09:11 UTC, tristan-gueguen requested changes
Voir commentaire dans la PR (lié à l'affichage)

2023-05-15 12:21 UTC, rtaieb commented
@tristan-gueguen Est ce que tu peux me dire sur quel navigateur tu obtiens ce résultat stp ? Sur Chrome desktop en affichage mobile ça passe bien : 
![image](https://github.com/MTES-MCT/mobilic/assets/35224301/799b4e2a-2f21-4f6f-aa98-8a1113be7998)

2023-05-17 13:13 UTC, tristan-gueguen commented
:green_circle: affichage ok maintenant. je me demande si ca rendrait pas mieux en mettant a la ligne pour chaque controle plutot que d'utiliser le join(' ; ') mais c'est comme tu sens

2023-05-17 13:13 UTC, tristan-gueguen approved these changes

2023-05-17 13:18 UTC, rtaieb commented
> green_circle affichage ok maintenant. je me demande si ca rendrait pas mieux en mettant a la ligne pour chaque controle plutot que d'utiliser le join(' ; ') mais c'est comme tu sens

On verra en test de l'équipe métier, comme c'était clairement spécifié comme ça, je l'ai fait mais ça sera pas grand chose à changer.

2023-05-17 13:25 UTC, merged