Feature/alert activity not finished
MTES-MCT/mobilic pull request #36
Opened 2021-09-10 15:33 UTC by rtaieb

Affichage d'une pop up dans la page de saisie des temps dans le cas où l'activité en cours dure plus de XX heures.$

https://trello.com/c/5o1egUDr/347-etq-salari%C3%A9-je-re%C3%A7ois-une-notification-lorsque-jai-une-activit%C3%A9-qui-dure-trop-longtemps-oubli

La pop up en question est WarningEndMissionModal.js .

Pour l'instant, le temps considéré comme "trop long" est fixé à 2mn (WarningEndMissionModal.js l.53), il reste à définir cette valeur et à la mettre dans un fichier de constante.

2021-09-13 08:34 UTC, rayannhamdan requested changes

2021-09-13 08:34 UTC, rayannhamdan commented on web/pwa/components/WarningEndMissionModal.js
> +    store.state.latestActivitySwitchExactTime;
Je pense qu'il n'y a pas besoin d'utiliser `latestActivitySwitchExactTime`ici. Cette variable sert uniquement pour l'affichage du timer les 5 premières minutes d'une nouvelle activité.

Comme l'alerte d'activité trop longue concernera vraisemblablement les activités de plus de 5 minutes, on peut simplifier le calcul de la `currentActivityDuration`.

2021-09-13 08:34 UTC, rayannhamdan commented on web/pwa/components/WarningEndMissionModal.js
> +  const shouldOpen =
Ici on dévie un peu du paradigme utilisé jusqu'à présent : la gestion de l'affichage des modals est gérée en dehors des modals elles-mêmes via un appel à `modals.open`.

Pour revenir au paradigme existant il faudrait déplacer toute la logique d'affichage dans un composant plus haut dans la hiérarchie (`CurrentActivity` par exemple).

Ceci dit, si tu préfères que la logique d'affichage soit dans la modal elle-même pour des raisons de lisibilité ou autre on peut laisser comme ça





2021-09-13 08:34 UTC, rayannhamdan commented on web/pwa/screens/CurrentActivity.js
> +  modals.open("warningEndMissionModal", {
cf. commentaire dans le fichier de la modal

2021-09-13 08:34 UTC, rayannhamdan commented on web/pwa/components/WarningEndMissionModal.js
> +        <CustomDialogActions>
Le composant `CustomDialogActions` ne devrait pas être sous le composant `DialogContent` (ce sont tous les deux des composants fils de `Dialog`)

2021-09-13 08:34 UTC, rayannhamdan commented on web/pwa/components/EndMission.js
> +                  Quelle est la date de fin de la mission&nbsp;?
```suggestion
                  Quelle est l'heure de fin de la mission&nbsp;?
```

2021-09-13 08:34 UTC, rayannhamdan commented on web/pwa/components/EndMission.js
> +                  label="Date de fin"
```suggestion
                  label="Heure de fin"
```

2021-09-13 08:34 UTC, rayannhamdan commented on web/pwa/components/WarningEndMissionModal.js
> +      latestActivityIdDurationWarningDismiss: latestActivity.id
Pour info la propriété `latestActivityIdDurationWarningDismiss` du store n'est pas enregistrée dans le `localStorage` => si je dismisse la modal puis que je refreshe la page la modal réapparaît.

je n'ai pas de préférence sur le comportement attendu (entre réafficher la modal à chaque refresh et ne l'afficher qu'une seule fois quelque soit le nombre de refreshs), qu'en penses-tu ?

2021-09-13 10:11 UTC, rtaieb commented on web/pwa/components/WarningEndMissionModal.js
> +      latestActivityIdDurationWarningDismiss: latestActivity.id
vu ensemble, le comportement est ok comme ça, je _resolve_ la conversation

2021-09-13 10:13 UTC, rtaieb commented on web/pwa/components/WarningEndMissionModal.js
> +        <CustomDialogActions>
ok, je corrige

2021-09-14 08:55 UTC, rayannhamdan approved these changes
C'est bon pour moi ! J'ai juste laissé une suggestion de renommage

2021-09-14 08:55 UTC, rayannhamdan commented on common/utils/events.js
> +export function getDuration(activity) {
```suggestion
export function getCurrentActivityDuration(activity) {
```

2021-09-14 08:55 UTC, rayannhamdan commented on web/pwa/screens/CurrentActivity.js
> +import { getDuration, getTime } from "common/utils/events";
```suggestion
import { getCurrentActivityDuration, getTime } from "common/utils/events";
```

2021-09-14 08:55 UTC, rayannhamdan commented on web/pwa/screens/CurrentActivity.js
> +      activityDuration={getDuration(latestActivity)}
```suggestion
      activityDuration={getCurrentActivityDuration(latestActivity)}
```

2021-09-14 09:22 UTC, merged