Add download certificate button
MTES-MCT/mobilic pull request #371
Opened 2023-06-29 06:35 UTC by rtaieb

https://trello.com/c/Ea1wHdij/1130-t%C3%A9l%C3%A9charger-un-certificat-pdf

2023-06-29 10:36 UTC, tristan-gueguen approved these changes

2023-06-29 11:11 UTC, tristan-gueguen requested changes
:orange_circle: on affiche le bouton pour les entreprises qui n'ont pas le certificat ?
Si oui, il n'y a pas trop d'explication lors de l'erreur quand on tente de le télécharger

2023-06-29 13:17 UTC, rtaieb commented
> 🟠 on affiche le bouton pour les entreprises qui n'ont pas le certificat ? Si oui, il n'y a pas trop d'explication lors de l'erreur quand on tente de le télécharger

haha effectivement :sweat_smile: , je n'affiche désormais le bouton que lorsque l'entreprise est certifiée, ce qui est plus logique

2023-06-30 08:04 UTC, tristan-gueguen approved these changes

2023-06-30 09:03 UTC, merged