Feature/optional mission name
MTES-MCT/mobilic pull request #38
Opened 2021-09-21 10:45 UTC by rtaieb

https://trello.com/c/S0iWlll5/344-etq-gestionnaire-je-peux-activer-d%C3%A9sactiver-la-saisie-du-nom-de-mission

Le gestionnaire peut maintenant choisir dans les paramètres si le nom de mission est demandé aux salariés lors de la saisie de leur temps.
Ce nom de mission se retrouve ensuite dans le backoffice.
Si le nom de mission n'est pas à renseigner, soit la colonne est masqué dans les tableaux, soit il est remplacé par "Mission du [start date]".

2021-09-27 08:38 UTC, rayannhamdan requested changes
Ok pour moi dans l'ensemble.

J'ai laissé une suggestion sur le renommage du texte associé au paramètre entreprise, et un point d'attention sur la gestion des "" dans le composant `NewMissionForm`

2021-09-27 08:38 UTC, rayannhamdan commented on web/admin/panels/Settings.js
> +          description="A la création d'une mission, le travailleur mobile doit obligatoirement saisir un nom pour celle-ci. Ce nom sera ensuite repris dans le backoffice pour une meilleure visibilité
On utilise pas trop le terme "backoffice" sur le site. Je reformulerais plutôt en disant que le nom de la mission est repris dans l'interface du gestionnaire pour un suivi plus fin du temps de travail/meilleure visibilité dans les outils de reporting

2021-09-27 08:38 UTC, rayannhamdan commented on web/pwa/components/history/Mission.js
> +  const actualDay = mission?.activities[0]?.startTime;
```suggestion
  const actualDay = mission?.startTime;
```

2021-09-27 08:38 UTC, rayannhamdan commented on web/common/NewMissionForm.js
> +  const [vehicle, setVehicle] = React.useState("");
Merci d'avoir corrigé cela. Il faut penser à modifier le `onSubmit` du formulaire pour quand mêmepasser des valeurs `null` (plutôt que des "") au `handleSubmit`des composants parents.

Sinon va faire des calls API avec des "" plutôt que des `null` sur les arguments optionnels, ce qui cause des erreurs 400

2021-09-27 13:37 UTC, rtaieb commented on web/common/NewMissionForm.js
> +  const [vehicle, setVehicle] = React.useState("");
en fait c'était mon setKilometerReading("") qui posait problème. Je l'ai corrigé et il n'y a plus d'erreur 400.

2021-09-30 12:07 UTC, rayannhamdan approved these changes

2021-09-30 12:44 UTC, merged