Feat/infractions no lic
MTES-MCT/mobilic pull request #392
Opened 2023-08-10 22:22 UTC by tristan-gueguen

https://trello.com/c/bPIOdWUy/1169-relever-les-infractions-modifier-les-infractions-retenues-dans-le-parcours-pas-de-lic

2023-08-11 12:31 UTC, rtaieb requested changes

2023-08-11 12:31 UTC, rtaieb commented on common/utils/regulation/alertTypes.js
> +  noPaperLic: "noLic"
:red_circle: Je n'ai plus accès une journée d'historique en tant que salarié, j'ai l'impression que ça vient de l'ajout de cette ligne.

2023-08-15 13:49 UTC, tristan-gueguen commented on web/control/components/UserReadAlerts.js
> +              disabled={!hasModifiedInfractions}
A faire dans ce ticket: https://trello.com/c/eHipqRTS/1209-modification-tous-parcours-contr%C3%B4les-mobilic-pas-de-lic-lic-papier

2023-08-16 09:11 UTC, rtaieb commented on web/control/components/UserReadTabs.js
> +                  totalAlertsNumber={props.totalAlertsNumber}
:green_circle: Etant donné qu'on passe {...props}, il est inutile de passes tous ses sous arguments de type :
```javascript
argumentName={props.argumentName}
```

2023-08-16 11:42 UTC, merged