Feature/add expenditures date
MTES-MCT/mobilic pull request #47
Opened 2021-10-04 07:28 UTC by rtaieb

https://trello.com/c/HJGQIiaj/375-pouvoir-pr%C3%A9ciser-le-jour-associ%C3%A9-%C3%A0-un-frais-en-cas-dune-mission-sur-2-jours

En relation avec https://github.com/MTES-MCT/mobilic-api/pull/26

2021-10-04 10:52 UTC, rayannhamdan reviewed
Les suggestions dont on a discuté en visio

2021-10-04 10:52 UTC, rayannhamdan commented on web/pwa/components/MissionDetails.js
> +                      currentExpenditures: regroupExpendituresByType(
Dans la vue "Jour" de l'historique, dans le détail d'une mission, il faudrait filtrer pour n'avoir que les frais de la mission associés au jour observé

2021-10-04 13:05 UTC, rayannhamdan requested changes
J'ai testé plusieurs cas en local :

* cas simple d'un utilisateur tout seul sur une mission qui dure plusieurs jours => nickel

* cas d'un utilisateur qui travaille en équipe => ça marche, avec la légère réserve que les coéquipiers retirés AVANT la fin de la mission n'ont pas de frais. Ce n'est pas grave, ils peuvent saisir leurs propres frais avant de valider.

* cas d'une modification des frais avant de valider (en solo ou en équipe) => nickel

* cas d'une modification des frais après modification des jours de mission => nickel

J'ai toutefois remarqué un problème sur la fin de mission  :

* lorsque je clique sur "Mission terminée" mais que la mission termine par une pause (càd que la dernière activité de la mission a une heure de fin) l'heure de fin de mission utilisée pour calculer les jours de frais est l'heure actuelle alors que ce devrait être l'heure de fin de l'activité => j'ai laissé une suggestion pour corriger ça

* dans la même veine, lorsque je clique sur "Terminer ma mission" depuis la modal, si ma mission se termine par une pause, la valeur minimale que je peux sélectionner pour l'heure de fin de mission (`missionEndTime`) est incorrecte : c'est `latestActivityStartTime` alors que ce devrait être `latestActivityEndOrStartTime`.

2021-10-04 13:41 UTC, rtaieb commented on common/utils/expenditures.js
> +      return spendingDates?.map(spendingDate => {
ça doit être un oubli, je l'enlève

2021-10-05 09:55 UTC, rayannhamdan approved these changes
Je vais refaire quelques tests fonctionnels

2021-10-05 13:19 UTC, merged