feat(control): export c1b file on control page
MTES-MCT/mobilic pull request #517
Opened 2024-05-03 10:27 UTC by tristan-gueguen

https://trello.com/c/xF6ugjwk/1132-export-c1b-depuis-la-vue-de-chaque-contr%C3%B4le

2024-05-16 13:21 UTC, sandrica89 requested changes

2024-05-16 13:21 UTC, sandrica89 commented on web/controller/components/details/ControllerControlExportMenu.js
> +        <MenuItem
:red_circle: Accessibilité : 
* le bouton au dessus n'est pas correctement lié au menu
* l'information concernant l'ouverture et la navigation du menu n'est pas transmise aux logiciels d'assistance

Voir https://mui.com/material-ui/react-menu/

2024-05-16 13:21 UTC, sandrica89 commented on web/controller/components/details/ControllerControlExportMenu.js
> +            modals.open("controllerExportC1BOne", {
:red_circle: Accessibilité : lors de l'ouverture de la modale, le focus n'est pas placé dessus, on ne peut pas naviguer au clavier.

Il y a un mix MUI et DSFR ici donc je ne sais pas trop si les attributs du DSFR vont fonctionner ici, cf https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/modale (on voit notamment un `aria-controls` qui pointe vers l'id de la modale).

2024-05-16 13:21 UTC, sandrica89 commented on web/controller/components/modals/ControllerExportC1BOne.js
> +    <Modal isOpen={open} hide={handleClose} size="lg">
:green_circle: Il existe dans DSFR un composant `<ModalClose>` pour gérer correctement le bouton de fermeture : https://dataesr.github.io/react-dsfr/?path=/docs/composants-modale-modal--modal-with-footer

2024-05-16 13:21 UTC, sandrica89 commented on web/controller/components/modals/ControllerExportC1BOne.js
> +        <Alert severity="warning">
:orange_circle: Accessibilité : ne pas le gérer ici, mais pour info les `Alert` ne sont pas faite pour afficher un message d'information comme ici. Il s'agit de message qui apparaisse sans géner la lecture en cours. C'est plutôt utiliser pour des traitements en tache de fond ou des réponses à des actions. Ici ce composant a un attribut `role=alert` qui n'est pas adapté.

2024-05-16 13:21 UTC, sandrica89 commented on web/controller/components/modals/ControllerExportC1BOne.js
> +            mail contact@mobilic.beta.gouv.fr.
:green_circle: On pourrait utiliser un lien mailto ici

2024-05-16 13:21 UTC, sandrica89 commented on web/controller/components/modals/ControllerExportC1BOne.js
> +            conducteur (ex.: certaines parties sont laissées vides faute de
:green_circle: Accessibilité : remplacer "ex.:" par "par exemple," (plus compréhensible avec un lecteur d'écran)

2024-05-16 13:21 UTC, sandrica89 commented on web/controller/components/modals/ControllerExportC1BOne.js
> +            <SignFilesCheckbox sign={sign} setSign={setSign} />
:red_circle: Accessibilité : ce composant n'est pas accessible, voir https://mui.com/material-ui/react-switch/#label

2024-05-16 13:21 UTC, sandrica89 commented on web/controller/components/modals/ControllerExportC1BOne.js
> +          title="téléchargement"
:red_circle: Accessibilité : le nom accessible (ici "téléchargement") doit à minima reprendre le texte visible (ici "Générer"). Ici, `title` n'a pas vraiment d'utiliser, on peut le supprimer et le nom accessible sera alors le nom visible à savoir "Générer".

2024-05-23 08:37 UTC, tristan-gueguen commented on web/controller/components/modals/ControllerExportC1BOne.js
> +        <Alert severity="warning">
Est-ce que tu veux créer un ticket sur ce sujet si pas déja fait ?

2024-05-23 09:08 UTC, tristan-gueguen commented on web/controller/components/modals/ControllerExportC1BOne.js
> +    <Modal isOpen={open} hide={handleClose} size="lg">
Est-ce que tu sais pourquoi il y a une props "hide" de prévue dans Modal, et ce fameux composant ModalClose. Je ne comprends pas trop pourquoi les deux existent.

2024-05-23 09:29 UTC, tristan-gueguen commented on web/controller/components/modals/ControllerExportC1BOne.js
> +            <SignFilesCheckbox sign={sign} setSign={setSign} />
Proposition de changement faite dans un commit

2024-05-29 11:52 UTC, tristan-gueguen commented on web/controller/components/details/ControllerControlExportMenu.js
> +            modals.open("controllerExportC1BOne", {
Ticket indépendant créé https://trello.com/c/TRDvWDM7/1537-rendre-les-modales-accessibles

2024-05-29 11:55 UTC, tristan-gueguen commented on web/controller/components/modals/ControllerExportC1BOne.js
> +        <Alert severity="warning">
Ticket créé https://trello.com/c/xp8b2KQR/1538-utilisation-non-accessible-des-alertes

2024-05-31 07:23 UTC, sandrica89 commented on web/controller/components/modals/ControllerExportC1BOne.js
> +    <Modal isOpen={open} hide={handleClose} size="lg">
Non je ne sais pas :shrug:

2024-05-31 07:25 UTC, sandrica89 approved these changes

2024-05-31 11:56 UTC, merged