Feat/dsfr alerts
MTES-MCT/mobilic pull request #564
Opened 2024-09-24 16:58 UTC by tristan-gueguen

2024-09-26 09:30 UTC, sandrica89 requested changes
Pour CustomAlert je pense aussi que c'est approprié de garder `Alert`.
Pour les accordéons, on devrait le transformer par du style.
Tu as essayé quand même de mettre les accordéons dans des Notice ?

2024-09-26 09:30 UTC, sandrica89 commented on web/control/VerifyXlsxSignature.js
> +            <Notice
:orange_circle: Je me demande si ici ce ne devrait pas être une alerte, car c'est en retour à un appel

2024-09-26 09:30 UTC, sandrica89 commented on web/pwa/modals/ActivityRevision.js
> +                    <Notice
Il manque le type="warning"

2024-09-26 09:39 UTC, sandrica89 commented
Il y aussi un soucis avec les tests qui ne passent pas.

2024-10-02 08:45 UTC, tristan-gueguen commented on web/common/Notice.d.ts
> +// toto.d.ts
:orange_circle:  au revoir toto

2024-10-03 07:43 UTC, sandrica89 approved these changes

2024-10-03 08:16 UTC, merged